### ISSUE TITLE
non-legacy

### ISSUE THREAD

**Issue by FranzSkuffka** [F1LT3R/markserv-legacy#2]
Hey there!

First off, markserv is great.

I would love emoji support but have no idea where to file the issue :)

**Comment by F1LT3R** [comment]
Hello,

Thanks!

Yeah sorry about the confusion there. There's a lot of pieces on the cutting room floor at the moment. (Currently working on the 3rd iteration).

Please file issues here: https://github.com/f1lt3r/markserv/issues
